### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by manuel-uberti** [chrisdone/zenburn#3]
Hi, a question, not an issue.

Do you plan to release Sunburn on MELPA? Asking because it is really a beautiful theme. :)

**Comment by manuel-uberti** [comment]
Actually, is it ok if I fork it and work on an updated version of Sunburn to put on MELPA? I.e.: without `color-theme`, for instance.

**Comment by chrisdone** [comment]
Feel free, I can't be bothered putting it on melpa. But you're free to do
what you want with it. :-)

**Comment by manuel-uberti** [comment]
Thank you!
